export const mockLeads = [
  {
    id: 1,
    name: 'Rajesh Sharma',
    mobile: '+91 9820144521',
    query: 'Looking for wholesale pricing catalog and minimum order quantity details for next month.',
  },
  {
    id: 2,
    name: 'Priya Patel',
    mobile: '+91 9811255432',
    query: 'Need a quick product demo scheduled for our procurement team this Thursday afternoon.',
  },
  {
    id: 3,
    name: 'Amit Verma',
    mobile: '+91 9717366543',
    query: 'Can someone call me back regarding annual maintenance contract packages and payment terms?',
  },
  {
    id: 4,
    name: 'Sunita Rao',
    mobile: '+91 9845077654',
    query: 'Interested in placing a bulk order for 200 units, please share quotation.',
  },
  {
    id: 5,
    name: 'Vikramaditya Deshmukh',
    mobile: '+91 9920388765',
    query: 'Do you provide customized branding options for corporate gifting orders before Diwali?',
  },
  {
    id: 6,
    name: 'Ananya Mukherjee',
    mobile: '+91 9830199876',
    query: 'Please send the latest product brochure and delivery timelines for Bengaluru location.',
  },
  {
    id: 7,
    name: 'Rohan Gupta',
    mobile: '+91 9810411234',
    query: 'Need clarification on warranty terms and after-sales service support in Pune region.',
  },
  {
    id: 8,
    name: 'Deepa Nair',
    mobile: '+91 9447022345',
    query: 'Looking for discounted pricing on recurring monthly supply orders for our retail outlet.',
  },
  {
    id: 9,
    name: 'Karthik Subramanian',
    mobile: '+91 9840133456',
    query: 'Can your sales representative visit our office tomorrow to discuss enterprise plan details?',
  },
  {
    id: 10,
    name: 'Pooja Agarwal',
    mobile: '+91 9829044567',
    query: 'Requesting quotation for express shipment of sample units to our Surat warehouse.',
  },
  {
    id: 11,
    name: 'Manish Tiwari',
    mobile: '+91 9415055678',
    query: 'Inquiring about immediate stock availability and payment options via bank transfer or UPI.',
  },
  {
    id: 12,
    name: 'Neha Kulkarni',
    mobile: '+91 9822066789',
    query: 'Want to schedule an online demonstration of your software platform for five users.',
  },
  {
    id: 13,
    name: 'Harish Reddy',
    mobile: '+91 9849077890',
    query: 'Please share updated rate card with applicable GST rates for commercial buyers.',
  },
  {
    id: 14,
    name: 'Sneha Joshi',
    mobile: '+91 9826088901',
    query: 'Need immediate assistance with order tracking and estimated delivery date to Hyderabad.',
  },
  {
    id: 15,
    name: 'Arvind Iyer',
    mobile: '+91 9841099012',
    query: 'Looking to replace our existing vendor, please share onboarding process and credit terms.',
  },
  {
    id: 16,
    name: 'Kavita Choudhury',
    mobile: '+91 9435011123',
    query: 'Is volume discount available if we order 500 pieces every single quarter?',
  },
  {
    id: 17,
    name: 'Sanjay Malhotra',
    mobile: '+91 9811122234',
    query: 'Please call me back regarding customized dimensions and packaging specifications for shipment.',
  },
  {
    id: 18,
    name: 'Divya Nambiar',
    mobile: '+91 9847133345',
    query: 'Interested in partnership and distributorship opportunities in the Delhi NCR regional market.',
  },
  {
    id: 19,
    name: 'Tarun Singhal',
    mobile: '+91 9818144456',
    query: 'Requesting a formal quotation for annual software license renewal for 20 workstations.',
  },
  {
    id: 20,
    name: 'Meera Sen',
    mobile: '+91 9831155567',
    query: 'Can we get sample pieces delivered before finalizing the full commercial contract?',
  },
  {
    id: 21,
    name: 'Alok Mishra',
    mobile: '+91 9450166678',
    query: 'Looking for fast delivery options and freight charges to Ahmedabad industrial zone.',
  },
  {
    id: 22,
    name: 'Ritu Bansal',
    mobile: '+91 9872177789',
    query: 'Please arrange a callback regarding priority technical support and service level agreement.',
  },
  {
    id: 23,
    name: 'Suresh Naidu',
    mobile: '+91 9848188890',
    query: 'Want to know return policy and replacement timeline for transit damaged goods.',
  },
  {
    id: 24,
    name: 'Shweta Ghosh',
    mobile: '+91 9830299901',
    query: 'Interested in standard subscription tier pricing for small business accounting software setup.',
  },
  {
    id: 25,
    name: 'Pankaj Bhatia',
    mobile: '+91 9810211122',
    query: 'Need quotation for urgent requirement of 50 units with invoice for GST input.',
  },
  {
    id: 26,
    name: 'Tanvi Hegde',
    mobile: '+91 9880222233',
    query: 'Can you provide references or client testimonials from similar businesses in Chennai?',
  },
  {
    id: 27,
    name: 'Gaurav Kapoor',
    mobile: '+91 9814233344',
    query: 'Inquiring if advance payment is mandatory or if milestone payments are supported.',
  },
  {
    id: 28,
    name: 'Swati Mahajan',
    mobile: '+91 9823244455',
    query: 'Please email full product catalog along with technical specifications and warranty sheet.',
  },
  {
    id: 29,
    name: 'Chetan Patil',
    mobile: '+91 9822255566',
    query: 'Looking for customized integration support with our existing inventory management software.',
  },
  {
    id: 30,
    name: 'Shalini Varma',
    mobile: '+91 9444266677',
    query: 'Requesting callback to discuss multi-branch deployment and centralized administrator access.',
  },
  {
    id: 31,
    name: 'Manoj Khatri',
    mobile: '+91 9829277788',
    query: 'Need estimated lead time for manufacturing and dispatching 300 custom branded units.',
  },
  {
    id: 32,
    name: 'Rupa Bhattacharya',
    mobile: '+91 9831288899',
    query: 'Are there any seasonal discount codes or introductory offers for first-time buyers?',
  },
  {
    id: 33,
    name: 'Dinesh Pillai',
    mobile: '+91 9847299900',
    query: 'Please share compliance certifications and quality assurance test reports for bulk purchase.',
  },
  {
    id: 34,
    name: 'Shilpa Goel',
    mobile: '+91 9811311122',
    query: 'Can we arrange a 15-minute introductory Zoom call with your technical sales specialist?',
  },
  {
    id: 35,
    name: 'Nitin Saxena',
    mobile: '+91 9412322233',
    query: 'Inquiring about credit period eligibility for registered micro and small enterprises.',
  },
  {
    id: 36,
    name: 'Aarti Mittal',
    mobile: '+91 9876333344',
    query: 'Want to confirm if door-to-door delivery and unpacking service is included.',
  },
  {
    id: 37,
    name: 'Vijay Menon',
    mobile: '+91 9846344455',
    query: 'Please share revised price quote after incorporating the 10 percent volume discount.',
  },
  {
    id: 38,
    name: 'Pallavi Dubey',
    mobile: '+91 9425355566',
    query: 'Looking for urgent quotation for spare parts and regular maintenance servicing schedule.',
  },
  {
    id: 39,
    name: 'Sandeep Jain',
    mobile: '+91 9828366677',
    query: 'Need details on minimum contract duration and cancellation policy for cloud services.',
  },
  {
    id: 40,
    name: 'Nandini Rao',
    mobile: '+91 9845377788',
    query: 'Can you provide expedited shipping to Kolkata for an upcoming client exhibition?',
  },
  {
    id: 41,
    name: 'Ajay Chauhan',
    mobile: '+91 9810388899',
    query: 'Inquiring if API documentation and sandbox testing environment are available for integration.',
  },
  {
    id: 42,
    name: 'Jyoti Deshpande',
    mobile: '+91 9822399900',
    query: 'Please arrange a site visit by your field engineer for installation assessment.',
  },
  {
    id: 43,
    name: 'Pranav Sundaram',
    mobile: '+91 9840411122',
    query: 'Requesting competitive quote comparison for tier-2 distributor pricing structure in Jaipur.',
  },
  {
    id: 44,
    name: 'Rashmi Soni',
    mobile: '+91 9827422233',
    query: 'Want to know if customer data is securely encrypted and compliant with standards.',
  },
  {
    id: 45,
    name: 'Mahesh Chawla',
    mobile: '+91 9814433344',
    query: 'Need clarification on payment gateway charges and supported international credit cards.',
  },
  {
    id: 46,
    name: 'Bhavna Sethi',
    mobile: '+91 9811444455',
    query: 'Looking to place a trial order of 10 units before placing bulk order.',
  },
  {
    id: 47,
    name: 'Kishore Yadav',
    mobile: '+91 9415455566',
    query: 'Please send proforma invoice with bank details for releasing immediate token advance.',
  },
  {
    id: 48,
    name: 'Preeti Namboodiri',
    mobile: '+91 9847466677',
    query: 'Can we customize the user interface with our company logo and brand theme?',
  },
  {
    id: 49,
    name: 'Varun Aggarwal',
    mobile: '+91 9818477788',
    query: 'Requesting urgent callback regarding contract terms renewal and SLA penalty clauses.',
  },
  {
    id: 50,
    name: 'Smita Kulkarni',
    mobile: '+91 9822488899',
    query: 'Inquiring about availability of dedicated account manager for enterprise-level priority support.',
  },
];
